//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_ders2_personel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExperience
    {
        public int ExperienceID { get; set; }
        public string ExperienceDate { get; set; }
        public string ExperienceDescription { get; set; }
        public string ExperienceTitle { get; set; }
    }
}
